title: Andrew Bortvin
baseurl: ""
url: "https://andrew-bortvin.github.io/"
google_analytics: # Tracking ID, e.g. "UA-000000-01"


# Author
author:
  name: Andrew Bortvin
  desc:
  email: abortvi2[at]jhu[dot]edu
  selfie: assets/IMG_7076.jpg

# social
social:
  email: true
  twitter: AndrewBortvin
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github: andrew-bortvin
  google_plus:
  instagram:
  keybase:
  linkedin: 
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:
  steam:
  tumblr:
  gitlab:
  vimeo:
  wordpress:
  youtube:
  default_txt: "Follow On"

# Build settings
markdown: kramdown

# Assets
sass:
  sass_dir: _sass
  style: compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink: /:year-:month-:day/:title
paginate_path: "/page:num/"
paginate: 5
exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gem"
  - "LICENSE"
  - "README.md"
